apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    app: hello
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30080    # fixed NodePort (optional) — you can omit nodePort and let k8s pick
